name: build-react16-demos

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # not support node>16.x and node<14.x

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v5
        with:
          version: 8

      - name: Build with-react16-ts
        working-directory: ./examples/with-react16-ts
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
          yarn run build
        env:
          CI: false
